// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepositories(arg1) {
  return window['go']['main']['App']['AddRepositories'](arg1);
}

export function AddRepository(arg1) {
  return window['go']['main']['App']['AddRepository'](arg1);
}

export function AddTag(arg1, arg2) {
  return window['go']['main']['App']['AddTag'](arg1, arg2);
}

export function AssignTag(arg1, arg2) {
  return window['go']['main']['App']['AssignTag'](arg1, arg2);
}

export function AssignTagToRepos(arg1, arg2) {
  return window['go']['main']['App']['AssignTagToRepos'](arg1, arg2);
}

export function GetAllStatuses() {
  return window['go']['main']['App']['GetAllStatuses']();
}

export function GetRepoStatus(arg1) {
  return window['go']['main']['App']['GetRepoStatus'](arg1);
}

export function GetRepositories() {
  return window['go']['main']['App']['GetRepositories']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function RefreshAll() {
  return window['go']['main']['App']['RefreshAll']();
}

export function RefreshRepository(arg1) {
  return window['go']['main']['App']['RefreshRepository'](arg1);
}

export function RemoveRepository(arg1) {
  return window['go']['main']['App']['RemoveRepository'](arg1);
}

export function RemoveTag(arg1) {
  return window['go']['main']['App']['RemoveTag'](arg1);
}

export function ScanForRepos(arg1) {
  return window['go']['main']['App']['ScanForRepos'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetGlobalPollInterval(arg1) {
  return window['go']['main']['App']['SetGlobalPollInterval'](arg1);
}

export function UnassignTag(arg1, arg2) {
  return window['go']['main']['App']['UnassignTag'](arg1, arg2);
}

export function UpdatePollInterval(arg1, arg2) {
  return window['go']['main']['App']['UpdatePollInterval'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSortOrder(arg1) {
  return window['go']['main']['App']['UpdateSortOrder'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
