// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {monitor} from '../models';

export function AddRepository(arg1:string):Promise<models.Repository>;

export function AddTag(arg1:string,arg2:string):Promise<models.Tag>;

export function AssignTag(arg1:number,arg2:number):Promise<void>;

export function AssignTagToRepos(arg1:Array<number>,arg2:number):Promise<void>;

export function GetAllStatuses():Promise<Record<number, monitor.RepoStatus>>;

export function GetRepoStatus(arg1:number):Promise<monitor.RepoStatus>;

export function GetRepositories():Promise<Array<models.Repository>>;

export function GetSettings():Promise<models.UserSettings>;

export function GetTags():Promise<Array<models.Tag>>;

export function RefreshAll():Promise<void>;

export function RefreshRepository(arg1:number):Promise<void>;

export function RemoveRepository(arg1:number):Promise<void>;

export function RemoveTag(arg1:number):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetGlobalPollInterval(arg1:number):Promise<void>;

export function UnassignTag(arg1:number,arg2:number):Promise<void>;

export function UpdatePollInterval(arg1:number,arg2:number):Promise<void>;

export function UpdateSettings(arg1:models.UserSettings):Promise<void>;

export function UpdateSortOrder(arg1:Array<number>):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
