name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'repo-mon'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'repo-mon'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'repo-mon'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppCore/build/actions/build/wails2@v4.0.0
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          sign: 'false'
          node-version: '22'
          go-version: '1.23'

      - name: Archive build
        shell: bash
        run: |
          ls -la build/bin/
          if [ "$RUNNER_OS" == "Linux" ]; then
            tar -czf repo-mon-linux-amd64.tar.gz -C build/bin .
          elif [ "$RUNNER_OS" == "Windows" ]; then
            mv build/bin/repo-mon build/bin/repo-mon.exe
            7z a repo-mon-windows-amd64.zip ./build/bin/repo-mon.exe
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cd build/bin && zip -ry ../../repo-mon-macos-universal.zip .
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-mon-${{ runner.os }}
          path: repo-mon-*.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
